### ISSUE TITLE
Styles for CRUD example

### ISSUE THREAD

**Issue by scabbiaza** [ivan-kleshnin/unredux#13]
TODO
- [x] ignore less/css on BE
- [x] check SSR

**Comment by scabbiaza** [comment]
@ivan-kleshnin, pls check PR
https://github.com/ivan-kleshnin/unredux/pull/12/files

(see my commit messages for clarification and motivation)

**Comment by scabbiaza** [comment]
Added changes after the discussion
https://github.com/ivan-kleshnin/unredux/pull/12/commits/19024d853dfdbbd13ec1fb83f55b492b6e036d4d

**Comment by ivan-kleshnin** [comment]
Done.
